### ISSUE TITLE
Excessive identical job parallelism in workflow

### ISSUE THREAD

**Issue by felddy** [cisagov/RedEye#47]
RedEye folk,

Could you take a look at your testing workflow.  When it kicks off it is occupying over half of our organization's available runners, and has starved out some of the other projects.
- Please document the purpose of `12` identical jobs running in parallel in the workflow.  e.g., the parallel tests are non-deterministic.
- Please consider [using `max-parallel`](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#defining-the-maximum-number-of-concurrent-jobs) to limit the matrix to a couple of jobs at a time if this parallelism isn't necessary. 

Thank,
@felddy 

https://github.com/cisagov/RedEye/blob/336919c97d620f40aaf403131ee922b7b169221d/.github/workflows/test.yml#L47-L51

https://github.com/cisagov/RedEye/blob/336919c97d620f40aaf403131ee922b7b169221d/.github/workflows/test.yml#L90-L94

**Comment by sang2925** [comment]
Sorry about this. I will reduce the amount of runners that the cypress tests are using.

**Comment by jsf9k** [comment]
> Sorry about this. I will reduce the amount of runners that the cypress tests are using.

Please don't forget to specify the purpose of running multiple, identical copies of the same job.  (The value of `containers` from the `matrix` strategy is not used as far as I can tell, which is why I am saying that all the jobs are identical.)

**Comment by sang2925** [comment]
Since RedEye is using the open source version of Cypress Cloud, we can take advantage of parallelization, allowing us to run all our integration and e2e tests, both red team and blue team versions in parallels across the VMs, resulting in faster, quicker builds. 
https://docs.cypress.io/guides/guides/parallelization#Overview
https://docs.cypress.io/guides/continuous-integration/github-actions#Parallelization

Although the jobs may look identical, different tests are ran within the jobs. 
For example:
https://github.com/cisagov/RedEye/actions/runs/3472932203/jobs/5804454782 
vs
https://github.com/cisagov/RedEye/actions/runs/3472932203/jobs/5804455116

**Comment by mcdonnnj** [comment]
This information about Cypress Cloud should be documented in the workflow. However there are only 20 slots available for GitHub Actions for the org so this workflow will completely starve the entire org of capacity until it has finished.

**Comment by GoldingAustin** [comment]
Is the entire org on the free plan with a 20 concurrent job limit? That would be excellent information to have so we can plan our action workflows around it.

**Comment by mcdonnnj** [comment]
@GoldingAustin Yes. This org is a free org with 20 runners in the pool.

**Comment by GoldingAustin** [comment]
Closing this for now, we've reduced the test actions to a single runner each #48
