### ISSUE TITLE
Bulk Host Hide

### ISSUE THREAD

**Issue by eddiezab** [cisagov/RedEye#6]
**Is your feature request related to a problem? Please describe.**
Importing logs with hosts that are not "engagement impactful" (e.g., sandboxes, test targets, etc). need to be manually hidden individually currently and for each host this currently takes 4 clicks, so this ends up being (4 * n) clicks where n is the number of hosts to hide.

**Describe the solution you'd like**
Reduce the number of clicks it takes to hide hosts, either through a bulk update, "checkbox/apply" all UX, or a context menu on the host, or a host-name filter upon import. 

**Describe alternatives you've considered**
As a work-around I've opened the sqlitedb in sqlitebrowser and modified the specific field/value in the db directly however, that appears to only affect the metadata and leaves empty information in the sidebar and the nodes remain in the graph.

![hidden field changed in db](https://user-images.githubusercontent.com/2179170/195894681-81b69658-1290-4fa2-9208-887ea080dfab.png)
 

**Additional context**
N/A

**Comment by cliffpyles** [comment]
@GoldingAustin I was going to take a shot at this feature, but I was unable to get the development environment to run Jest for my tests. Technically it would run Jest, as long as I was just testing a function. It didn't play well with rendering the components with React Testing Library though.

I'm not very familiar with the nrwl tools or vite though, so it's definitely possible it was a user error. 😄 From what I can tell it wasn't recognizing TypeScript though.

Can you tell me if Jest and React Testing Library should be compatible with this environment? I saw some Jest usage in parts of the repo, but not in all of the applications. I wasn't able to find any usage of React Testing Library though.

Thanks for contributing this awesome project btw! I can't wait to make some contributions!

**Comment by GoldingAustin** [comment]
Thanks for the feedback, exciting to see improvement ideas from your use case!

@cliffpyles We do our UI testing through [Cypress](https://www.cypress.io) instead of Jest. The environment isn't currently setup to run any React tests through Jest & React Testing Library. We may update our configuration to be compatible at some point in the future, but for now it's not our priority. @sang2925 Is our testing expert and can answer any questions about Cypress. Thanks so much for being willing to contribute!

**Comment by cliffpyles** [comment]
Thanks @GoldingAustin! I love using Cypress for my integration and end-to-end tests. It's such a great tool!

Currently I'm focused on testing the input and output of my components though, so I'm in need of some unit tests. I'm happy to use other tools to write them if needed, but I noticed that both Jest and React Testing Library were already in the package.json, so I was going to use those because I assumed it was the preferred approach. I really was just going to use RTL for rendering the component though. Then I planned to generate snapshots with Jest. Any thoughts @sang2925?

**Comment by GoldingAustin** [comment]
Cypress [does more](https://docs.cypress.io/guides/overview/why-cypress#Test-types) than just integration and end-to-end tests, and we’d like to keep client testing within Cypress. We are not planning on supporting Jest & RTL unit tests for the client React components at this time.

**Comment by cliffpyles** [comment]
@GoldingAustin Understood. I'll leverage Cypress then.

To be clear though – the project does want outside contributors correct? Or am I making incorrect assumptions? I know this is a tool that is government backed, but the goal is to be open, collaborative, and engaged with the open source community, correct?

**Comment by GoldingAustin** [comment]
Yes, we definitely do and very much appreciate you wanting to contribute! We will continue to engage and are actively looking for community feedback and contributions. Part of that responsibility in open-source for us is fostering collaboration while also maintaining the order, standards, and practices of the codebase.

**Comment by cliffpyles** [comment]
Sounds great. Thank you for clarifying!

I've worked for open source companies in the past. I previously worked at RedHat. I can appreciate all of the hard work your team will be putting into the project. Collaboration and transparency is not always an easy thing to achieve. It's worth it though! Keep up the awesome work!

Here are a couple of resources about open source. I hope you find them useful!

https://opensource.com/open-source-way

https://www.theopensourceway.org/the_open_source_way-guidebook-2.0.html

**Comment by cliffpyles** [comment]
@GoldingAustin It looks like you began some work on this feature previously, but commented it out. I'm using the commented code I found in `ControlBar.tsx`. Is there any other previous work that I should try to leverage for this feature?

**Comment by GoldingAustin** [comment]
@cliffpyles That commented code was for filtering within a panel. For bulk selecting, we have a similar idea at the bottom of that same component with selecting commands in a multi-command comment!
